# Generated by Django 3.1.3 on 2020-12-02 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0006_auto_20201202_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('autosave', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quick_save', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quick_save', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='QuicksaveTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('wallet to quicksave', 'wallet to quicksave'), ('quicksave to wallet', 'quicksave to wallet'), ('bank account to quicksave', 'bank account to quicksave'), ('quicksave to bank account', 'quicksave to bank account')], default='wallet to quicksave', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quicksave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.quicksave')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
