# Generated by Django 3.1.3 on 2020-12-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicksave',
            name='autosave_days_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
