# Generated by Django 3.1.3 on 2020-12-02 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_quicksave_autosave_days_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quicksave',
            old_name='autosave_days_interval',
            new_name='day_interval',
        ),
        migrations.AlterField(
            model_name='quicksavetransaction',
            name='quicksave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='savings.quicksave'),
        ),
    ]
