# Generated by Django 3.1.3 on 2020-12-09 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0007_auto_20201203_0002'),
        ('savings', '0003_auto_20201202_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targeted_saving', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('active', models.BooleanField(default=False)),
                ('autosave', models.BooleanField(default=False)),
                ('day_interval', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target_save', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target_save', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='TargetSavingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('wallet to targetsave', 'wallet to targetsave'), ('targetsave to wallet', 'targetsave to wallet'), ('bank account to targetsave', 'bank account to targetsave'), ('targetsave to bank account', 'targetsave to bank account')], default='wallet to targetsave', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_save', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='savings.targetsave')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
