# Generated by Django 3.1.3 on 2020-12-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_auto_20201211_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicksave',
            name='last_saved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetsave',
            name='last_saved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
