# Generated by Django 3.1.3 on 2020-12-15 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0006_auto_20201211_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointsaving',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='joint_saving', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jointsaving',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='jointsaving',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jointsaving',
            name='frequency',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='weekly', max_length=64),
        ),
        migrations.AddField(
            model_name='jointsaving',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joint_savings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jointsaving',
            name='name',
            field=models.CharField(default='yyy', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jointsaving',
            name='total',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.CreateModel(
            name='JointSavingTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_types', models.CharField(choices=[('wallet to joint save', 'wallet to joint save'), ('joint save to wallet', 'joint save to wallet')], default='wallet to joint save', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('joint_saving', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='savings.jointsaving')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
