# Generated by Django 3.1.3 on 2020-12-15 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0007_auto_20201215_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointsaving',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_joint_saving', to=settings.AUTH_USER_MODEL),
        ),
    ]
