# Generated by Django 3.1.3 on 2020-12-15 16:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0008_auto_20201215_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JointSavingTransactions',
            new_name='JointSavingTransaction',
        ),
    ]
