# Generated by Django 3.1.3 on 2020-12-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0010_auto_20201215_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jointsavetransaction',
            old_name='transaction_types',
            new_name='transaction_type',
        ),
    ]
