# Generated by Django 3.1.3 on 2020-12-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0011_auto_20201216_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jointsavetransaction',
            old_name='joint_saving',
            new_name='joint_save',
        ),
    ]
