# Generated by Django 3.1.3 on 2020-12-18 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0014_auto_20201218_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointsave',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_joint_saving', to=settings.AUTH_USER_MODEL),
        ),
    ]
