# Generated by Django 3.1.3 on 2020-12-21 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_wallet_wallet_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0015_auto_20201218_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetsave',
            old_name='active',
            new_name='joint',
        ),
        migrations.RenameField(
            model_name='targetsave',
            old_name='autosave_amount',
            new_name='targeted_amount',
        ),
        migrations.RemoveField(
            model_name='targetsave',
            name='autosave',
        ),
        migrations.RemoveField(
            model_name='targetsave',
            name='day_interval',
        ),
        migrations.RemoveField(
            model_name='targetsave',
            name='last_saved',
        ),
        migrations.RemoveField(
            model_name='targetsave',
            name='targeted_saving',
        ),
        migrations.AddField(
            model_name='targetsave',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='targetsave',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='targetsave',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joint_target_savings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='targetsave',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='jointsavetransaction',
            name='joint_save',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='savings.jointsave'),
        ),
        migrations.AlterField(
            model_name='targetsave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_savings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='targetsave',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_savings', to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='targetsavingtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_saving_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TargetSaveAutoSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('day_interval', models.IntegerField(blank=True, null=True)),
                ('autosave_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_saved', models.DateField(blank=True, null=True)),
                ('target_save', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autosave', to='savings.targetsave')),
            ],
        ),
    ]
