# Generated by Django 3.1.3 on 2020-12-22 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0016_auto_20201221_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointsavetrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joint_save_tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
