# Generated by Django 3.1.3 on 2021-01-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0017_auto_20201222_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointsavetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Wallet To Joint Save', 'Wallet To Joint Save'), ('Joint Save To Wallet', 'Joint Save To Wallet')], default='Wallet To Joint Save', max_length=64),
        ),
        migrations.AlterField(
            model_name='quicksavetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Wallet To Quicksave', 'Wallet To Quicksave'), ('Quicksave To Wallet', 'Quicksave To Wallet'), ('Bank Account To Quicksave', 'Bank Account To Quicksave'), ('Quicksave To Bank Account', 'Quicksave To Bank Account')], default='Wallet To Quicksave', max_length=64),
        ),
        migrations.AlterField(
            model_name='targetsavingtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Wallet To Targetsave', 'Wallet To Targetsave'), ('Targetsave To Wallet', 'Targetsave To Wallet'), ('Bank Account To Targetsave', 'Bank Account To Targetsave'), ('Targetsave To Bank Account', 'Targetsave To Bank Account')], default='Wallet To Targetsave', max_length=64),
        ),
    ]
