# Generated by Django 3.1.3 on 2021-01-07 21:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0018_auto_20210101_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jointsavetransaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='quicksavetransaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='targetsavingtransaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='jointsave',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='jointsave',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
