# Generated by Django 3.1.3 on 2021-01-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0019_auto_20210107_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsave',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
