# Generated by Django 3.1.3 on 2020-11-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20201119_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='password',
            field=models.CharField(default='none', max_length=128),
        ),
    ]
