# Generated by Django 3.1.3 on 2020-11-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='password',
            field=models.BinaryField(default=b''),
        ),
    ]
