# Generated by Django 3.1.3 on 2020-12-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20201121_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='amount',
            new_name='balance',
        ),
    ]
