# Generated by Django 3.1.3 on 2020-12-03 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0006_auto_20201202_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recieved_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
