# Generated by Django 3.1.3 on 2020-12-11 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0007_auto_20201203_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings_account', models.CharField(choices=[('quick save', 'quick save'), ('joint save', 'joint save'), ('Target Save', 'Target Save')], default='quick save', max_length=64)),
                ('transaction_type', models.CharField(choices=[('savings to wallet', 'savings to wallet'), ('wallet to savings', 'wallet to savings')], default='wallet to savings', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
