# Generated by Django 3.1.3 on 2020-12-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_savingtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
