# Generated by Django 3.1.3 on 2021-01-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_auto_20201228_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttransaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='savingtransaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='savingtransaction',
            name='savings_account',
            field=models.CharField(choices=[('Quick save', 'Quick save'), ('Joint save', 'Joint save'), ('Target Save', 'Target Save')], default='Quick save', max_length=64),
        ),
    ]
