export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";
export const GET_WALLET = "GET_WALLET";
export const SET_WALLET = "SET_WALLET";
export const FUND_WALLET = "FUND_WALLET";
export const SEND_CASH = "SEND_CASH";
export const GET_QUICKSAVE = "GET_QUICKSAVE";
export const DEPOSIT_QUICK_SAVE = "DEPOSIT_QUICK_SAVE";
export const QUICK_SAVE_CASH_OUT = "QUICK_SAVE_CASH_OUT";
export const AUTOSAVE_QUICK_SAVE = "AUTOSAVE_QUICK_SAVE";
export const GET_TARGETSAVE = "GET_TARGETSAVE";
export const TARGETSAVE_CASH_OUT = "TARGETSAVE_CASH_OUT";
export const TARGETSAVE_DEPOSIT = "TARGETSAVE_DEPOSIT";
export const DELETE_TARGETSAVE = "DELETE_TARGETSAVE";
export const TARGETSAVE_AUTOSAVE = "TARGETSAVE_AUTOSAVE";
export const GET_JOINT_TARGETSAVE = "GET_JOINT_TARGETSAVE";
export const JOINT_TARGETSAVE_CASH_OUT = "JOINT_TARGETSAVE_CASH_OUT";
export const JOINT_TARGETSAVE_DEPOSIT = "JOINT_TARGETSAVE_DEPOSIT";
export const DELETE_JOINT_TARGETSAVE = "DELETE_JOINT_TARGETSAVE"
export const INVITE_JOINT_TARGETSAVE = "INVITE_JOINT_TARGETSAVE"
export const LEAVE_JOINT_TARGETSAVE = "LEAVE_JOINT_TARGETSAVE"

export const GET_JOINT_SAVE = "GET_JOINT_SAVE";
export const DEPOSIT_JOINT_SAVE = "DEPOSIT_JOINT_SAVE";
export const DISBAND_JOINT_SAVE = "DISBAND_JOINT_SAVE";
export const LEAVE_JOINT_SAVE = "LEAVE_JOINT_SAVE";

export const GET_BANKS = "GET_BANKS";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const MAKE_PAYMENT = "MAKE_PAYMENT";

export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const BVN_VERIFIED = "BVN_VERIFIED"

export const UPDATE_WALLET_ID = "UPDATE_WALLET_ID"