# Generated by Django 3.1.3 on 2020-12-28 01:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('investment_type', models.CharField(choices=[('fixed income', 'fixed income')], default='fixed income', max_length=32)),
                ('payout_type', models.CharField(choices=[('capital + profit', 'capital + profit'), ('profit', 'profit')], max_length=32)),
                ('units', models.IntegerField()),
                ('units_left', models.IntegerField()),
                ('amount_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('approved', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('yearly_profit_percent', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('date_create', models.DateField(auto_now_add=True)),
                ('investors', models.ManyToManyField(blank=True, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvesmentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_bougth', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='investment.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
