# Generated by Django 3.1.3 on 2021-01-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invesmenttransaction',
            old_name='unit_bougth',
            new_name='units_bought',
        ),
    ]
