# Generated by Django 3.1.3 on 2021-01-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_auto_20210121_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
